blank_issues_enabled: false
contact_links:
  - name: "Report issues"
    url: https://www.jenkins.io/participate/report-issue/redirect/#16033/maven-plugin
    about: Please use Jira to report new issues
